### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by Enigmatisms** [SYSU-STAR/STAR-Searcher#1]
Hi, I am an undergrad in XJTU and I am very interested in this project. I wonder when the code will be available. Thank you!

**Comment by 1461891375** [comment]
Hi, I am an undergrad in HNU and I am very interested in this project ,too. I wonder when the code will be available. Thank you!

**Comment by Poaos** [comment]
Congratulations on the successful publication of your article in RAL, looking forward to the code. 😊😍

**Comment by ChanJoon** [comment]
+1

**Comment by larsoncs** [comment]
+1

**Comment by larsoncs** [comment]
+1

**Comment by ymLuo1214** [comment]
Hey guys👋, the code is now open-source! 🎉 Hope it helps you out in your projects. If you run into any issues or have any questions, feel free to reach out here – always happy to help! 🚁✨
