### ISSUE TITLE
运行exploration_node时gazebo报错

### ISSUE THREAD

**Issue by MO-Huang** [SYSU-STAR/STAR-Searcher#4]
作者您好，非常感谢您开源了Star-Searcher的代码以供学习交流。在跑Star-Searcher代码的时候，我按照README中的提示，①先开gazebo里环境的仿真②再开gazebo里无人机的仿真③开rviz④运行搜索的代码。每次步骤④进行一会之后gazebo就报错，报错信息附在下方。经过排查，是运行exploration_node时gazebo报错的。尝试了很多方法都没能找到报错的原因，不知作者可否指点一下问题可能出在哪，或是应该怎么样调试并找到问题呢，万分感谢！

报错信息：
malloc(): memory corruption
Aborted (core dumped)
[gazebo-2] process has died [pid 104283, exit code 134....
![gazebo报错信息](https://github.com/user-attachments/assets/a5c29fa1-566f-481c-90b4-80f824255e19)

**Comment by ymLuo1214** [comment]
您好，
这个报错我在测试时没有遇到过，但根据报错信息来看，可能是可用内存不足导致的，可以尝试
1. 修改感知的范围，让地图更新的ray_cast距离减少，这一点也会对算法效果产生影响。
2. 生成一个简单的场景并减少场景中的模型，以及在simulator的配置文件里减少lidar仿真的光线采样，后者可能会影响算法效果。

**Comment by MO-Huang** [comment]
感谢您的耐心回复！今天我尝试在Ubuntu20.04.6上运行代码之后这个问题就不存在了（之前是Ubuntu18.04.6）。

**Comment by MO-Huang** [comment]
感谢您的耐心回复！今天我尝试在Ubuntu20.04.6上运行代码之后这个问题就不存在了（之前是Ubuntu18.04.6）。
